(()=>{
const opening=document.getElementById('opening'),sound=document.getElementById('soundToggle'),langBtn=document.getElementById('langToggle');
const params=new URLSearchParams(location.search),name=params.get('name')||'Yến Nhi';
let lang='en',playing=false,ctx,master,dry,wet,next=0,bar=0,timer;
try{lang=localStorage.getItem('daube_lang')||'en'}catch{}
const D={
 en:{open:'A rose, before the gift.',body:'A quiet enchanted reveal, made for one name at a time.',for:'For',openRose:'Open the rose',copy:'Copy personal link',prepared:'Prepared with first light for',enterVault:'Enter the gift vault ↓',vault:'Six keepsakes, each with its own little weather.',congrats:'For',ceremony:'A page carrying your name, one rose, one score, and a collection prepared with care.',certificateLink:'Keep the certificate →',presented:'Presented to',certBody:'For arriving early, bringing warmth into the garden, and becoming part of the story from its first light.',print:'Print certificate',faqTitle:'Only the useful bits.',q1:'What is this page?',a1:'A personalized D’AUBE digital gift experience.',q2:'Can the name change?',a2:'Yes. Add ?name=Your%20Name to the URL.',q3:'Do I need to buy anything?',a3:'No. This is a goodwill digital gift experience.',q4:'Is the music original?',a4:'Yes. The Nocturne Mix is composed for this Rose Garden experience.',sound:'♫ Sound',pause:'❚❚ Pause',copied:'Personal link copied.'},
 vi:{open:'Một đóa hồng, rồi mới tới món quà.',body:'Một màn hé mở ma mị, dịu và dành riêng cho từng cái tên.',for:'Dành cho',openRose:'Mở đóa hồng',copy:'Sao chép link cá nhân',prepared:'Được chuẩn bị cùng first light cho',enterVault:'Bước vào kho quà ↓',vault:'Sáu món kỷ vật, mỗi món mang một kiểu thời tiết riêng.',congrats:'Dành cho',ceremony:'Một trang mang tên bạn, một đóa hồng, một bản nhạc, và một bộ quà được chuẩn bị cẩn thận.',certificateLink:'Giữ lại chứng nhận →',presented:'Trao tặng cho',certBody:'Vì đã đến sớm, mang hơi ấm vào khu vườn, và trở thành một phần của câu chuyện từ ánh sáng đầu tiên.',print:'In chứng nhận',faqTitle:'Chỉ giữ lại những điều cần biết.',q1:'Trang này là gì?',a1:'Một trải nghiệm quà tặng digital được cá nhân hóa của D’AUBE.',q2:'Có thể đổi tên không?',a2:'Có. Thêm ?name=Ten%20Ban vào URL.',q3:'Có cần mua gì không?',a3:'Không. Đây là trải nghiệm quà tặng thiện chí.',q4:'Nhạc có phải nhạc gốc không?',a4:'Có. Nocturne Mix được làm riêng cho Rose Garden.',sound:'♫ Âm thanh',pause:'❚❚ Tạm dừng',copied:'Đã sao chép link cá nhân.'},
 fr:{open:'Une rose, avant le cadeau.',body:'Un dévoilement enchanté, calme et préparé pour un seul nom à la fois.',for:'Pour',openRose:'Ouvrir la rose',copy:'Copier le lien personnel',prepared:'Préparé avec la première lumière pour',enterVault:'Entrer dans le coffre ↓',vault:'Six souvenirs, chacun avec sa propre météo.',congrats:'Pour',ceremony:'Une page portant votre nom, une rose, une musique et une collection préparée avec soin.',certificateLink:'Garder le certificat →',presented:'Présenté à',certBody:'Pour être arrivé(e) tôt, avoir apporté de la chaleur dans le jardin, et être devenu(e) partie de l’histoire dès sa première lumière.',print:'Imprimer le certificat',faqTitle:'Seulement l’essentiel.',q1:'Qu’est-ce que cette page ?',a1:'Une expérience cadeau numérique personnalisée de D’AUBE.',q2:'Peut-on changer le nom ?',a2:'Oui. Ajoutez ?name=Votre%20Nom à l’URL.',q3:'Faut-il acheter quelque chose ?',a3:'Non. Il s’agit d’un cadeau numérique de gratitude.',q4:'La musique est-elle originale ?',a4:'Oui. Le Nocturne Mix est composé pour cette expérience Rose Garden.',sound:'♫ Son',pause:'❚❚ Pause',copied:'Lien personnel copié.'}
};
['recipient','revealName','ceremonyName','certificateName'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=name});
function tr(){const d=D[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-k]').forEach(e=>{const v=d[e.dataset.k];if(v)e.textContent=v});langBtn.textContent=lang.toUpperCase();sound.textContent=playing?d.pause:d.sound;try{localStorage.setItem('daube_lang',lang)}catch{}}
langBtn.addEventListener('click',()=>{lang=lang==='en'?'vi':lang==='vi'?'fr':'en';tr()});
const gifts=[
 ['https://static.metricool.com/planner/202609/6777444-file-2744650710188830546.png','First Light Boulevard','Golden beginnings.'],
 ['https://static.metricool.com/planner/202609/6777444-file-11330638333236336577.png','Rainy Reset','Quiet weather, softer breath.'],
 ['https://static.metricool.com/planner/202609/6777444-file-8158469004589067581.png','Sunday Slow','A warm permission to rest.'],
 ['https://static.metricool.com/planner/202609/6777444-file-9274001016095624913.png','Sweet Café','A little sweetness.'],
 ['https://static.metricool.com/planner/202609/6777444-file-14929937988927629993.png','Creator Desk','A place to make things.'],
 ['https://static.metricool.com/planner/202609/6777444-file-3695421190270616373.png','Curiosity Arcade','A tiny door to curiosity.']
];
document.getElementById('giftGrid').innerHTML=gifts.map((g,i)=>`<article class="gift"><img loading="lazy" src="${g[0]}" alt="${g[1]}"><div class="gift-copy"><span>${i<3?'Wallpaper':'Keepsake'}</span><h3>${g[1]}</h3><p>${g[2]}</p><a href="${g[0]}" target="_blank" rel="noopener">Open gift ↗</a></div></article>`).join('');
function spawnPetals(){const host=document.querySelector('.petal-field');if(!host||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<10;i++){const p=document.createElement('i');p.style.cssText=`position:absolute;left:${20+Math.random()*60}%;top:${20+Math.random()*42}%;width:${10+Math.random()*10}px;height:${7+Math.random()*8}px;border-radius:65% 35% 65% 35%;background:linear-gradient(#d44f6c,#7d1730);opacity:0;box-shadow:0 8px 16px rgba(91,13,35,.18);animation:daubePetal ${1.2+Math.random()*1.3}s ${Math.random()*.55}s cubic-bezier(.2,.7,.2,1) forwards;--dx:${-45+Math.random()*90}px;--dy:${100+Math.random()*130}px`;host.appendChild(p);p.addEventListener('animationend',()=>p.remove())}}
const style=document.createElement('style');style.textContent='@keyframes daubePetal{0%{opacity:0;transform:translate(0,0) rotate(0)}15%{opacity:.9}100%{opacity:0;transform:translate(var(--dx),var(--dy)) rotate(220deg)}}';document.head.appendChild(style);
function openRose(){if(opening.classList.contains('is-open'))return;opening.classList.add('is-open');spawnPetals();startMusic();}
document.getElementById('openRose').addEventListener('click',openRose);
document.getElementById('copyLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);document.getElementById('copyStatus').textContent=D[lang].copied}catch{}});
document.getElementById('printCert').addEventListener('click',()=>print());
const BPM=72,B=60/BPM,BAR=B*3,progression=[[50,53,57,60],[46,50,53,57],[53,57,60,64],[48,52,55,60],[43,46,50,53],[50,53,57,62],[45,49,52,57],[50,53,57,60]],mel=[[74,77,81],[72,77,79],[77,81,84],[72,76,79],[70,74,77],[74,79,81],[73,76,81],[74,77,81]],hz=n=>440*Math.pow(2,(n-69)/12);
function impulse(c){const l=c.sampleRate*2.8,b=c.createBuffer(2,l,c.sampleRate);for(let k=0;k<2;k++){const d=b.getChannelData(k);for(let i=0;i<l;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/l,3.2)}return b}
function initAudio(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.33;dry=ctx.createGain();wet=ctx.createGain();dry.gain.value=.72;wet.gain.value=.28;const rev=ctx.createConvolver(),comp=ctx.createDynamicsCompressor();rev.buffer=impulse(ctx);comp.threshold.value=-22;comp.knee.value=24;comp.ratio.value=2.2;comp.attack.value=.01;comp.release.value=.55;dry.connect(comp);wet.connect(rev);rev.connect(comp);comp.connect(master);master.connect(ctx.destination);next=ctx.currentTime+.08;timer=setInterval(schedule,260)}
function note(n,t,d=.8,v=.035,type='triangle',pan=0,cut=2600){const o=ctx.createOscillator(),g=ctx.createGain(),p=ctx.createStereoPanner(),f=ctx.createBiquadFilter();o.type=type;o.frequency.value=hz(n);f.type='lowpass';f.frequency.value=cut;p.pan.value=pan;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(f);f.connect(g);g.connect(p);p.connect(dry);p.connect(wet);o.start(t);o.stop(t+d+.05)}
function pad(ns,t){ns.slice(0,3).forEach((n,i)=>{note(n+12,t,BAR*.95,.010,'sawtooth',(i-1)*.25,850);note(n+24,t+.02,BAR*.82,.004,'sine',(1-i)*.18,3800)})}
function barPlay(i,t){const c=progression[i],m=mel[i];pad(c,t);note(c[0]-12,t,B*1.8,.042,'triangle',-.16,1200);note(c[0]-5,t+B*1.5,B*.9,.021,'sine',.18,1600);m.forEach((n,j)=>note(n,t+j*B,.56,.030,j===1?'sine':'triangle',j===1?-.12:.1,3000));note(m[1]+12,t+B*1.52,.42,.009,'sine',.28,5200)}
function schedule(){if(!ctx||ctx.state!=='running')return;while(next<ctx.currentTime+BAR*1.7){barPlay(bar%8,next);bar++;next+=BAR}}
async function startMusic(){initAudio();if(ctx.state==='suspended')await ctx.resume();playing=true;schedule();tr()}
async function pauseMusic(){if(ctx&&ctx.state==='running')await ctx.suspend();playing=false;tr()}
sound.addEventListener('click',()=>playing?pauseMusic():startMusic());
tr();
})();