const CDN={motion:'https://cdn.jsdelivr.net/npm/motion@13.2.0/+esm',lenis:'https://cdn.jsdelivr.net/npm/lenis@1.3.26/+esm',ogl:'https://cdn.jsdelivr.net/npm/ogl@1.0.11/+esm'};
async function safeImport(url){try{return await import(url)}catch(error){console.warn('[D’AUBE V10] optional module fallback',url,error);return null}}
function canWebGL(){try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}}
function detectTier(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,save=!!navigator.connection?.saveData,mem=Number(navigator.deviceMemory||4),cores=Number(navigator.hardwareConcurrency||4),webgl=canWebGL();if(reduced||save||!webgl||mem<=2||cores<=2)return'low';if(mem>=8&&cores>=8&&innerWidth>=900)return'high';return'medium'}
const tier=detectTier();document.body.dataset.vfxTier=tier;document.body.classList.add('vfx-'+tier);
const opening=document.getElementById('opening'),rose=document.querySelector('.rose-reliquary');let motionApi=null,lenis=null;
async function initMotion(){if(tier==='low')return;motionApi=await safeImport(CDN.motion);if(!motionApi)return;const{animate,inView,stagger}=motionApi;animate('.opening-copy > *',{opacity:[0,1],y:[14,0]},{delay:stagger(.06),duration:.75,ease:[.2,.8,.2,1]});animate('.rose-reliquary',{opacity:[0,1],scale:[.97,1],y:[18,0]},{duration:1.05,ease:[.2,.8,.2,1]});document.querySelectorAll('.gift,.cert-paper,.ceremony-copy').forEach(el=>inView(el,()=>animate(el,{opacity:[.1,1],y:[22,0]},{duration:.7,ease:[.2,.75,.2,1]}),{amount:.1,margin:'-8% 0px -8% 0px'}))}
async function initLenis(){if(tier==='low'||!matchMedia('(pointer:fine)').matches)return;const mod=await safeImport(CDN.lenis);if(!mod?.default)return;try{lenis=new mod.default({lerp:.085,smoothWheel:true,wheelMultiplier:.84});const raf=t=>{lenis?.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf)}catch(error){console.warn('[D’AUBE V10] Lenis fallback',error)}}
async function initOGL(){if(tier==='low')return false;const mod=await safeImport(CDN.ogl);if(!mod)return false;const canvas=document.getElementById('roseFx');if(!canvas)return false;try{const{Renderer,Program,Mesh,Triangle}=mod,renderer=new Renderer({canvas,alpha:true,dpr:Math.min(devicePixelRatio,tier==='high'?1.6:1.15)}),gl=renderer.gl;gl.clearColor(0,0,0,0);const geometry=new Triangle(gl),vertex=`attribute vec2 position;varying vec2 vUv;void main(){vUv=position*.5+.5;gl_Position=vec4(position,0.,1.);}`,fragment=`precision highp float;varying vec2 vUv;uniform float uTime;uniform vec2 uResolution;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1.,0.)),f.x),mix(h(i+vec2(0.,1.)),h(i+vec2(1.,1.)),f.x),f.y);}void main(){vec2 uv=vUv;float t=uTime*.09;float f=n(uv*4.2+vec2(t,-t*.62));float g=n(uv*7.7+vec2(-t*.38,t*.74));vec2 p=uv-vec2(.5,.5);p.x*=uResolution.x/uResolution.y;float halo=exp(-dot(p,p)*2.8);float ring=exp(-abs(length(p)-.29)*18.);vec3 gold=vec3(1.,.72,.39),rose=vec3(.68,.08,.19);vec3 col=mix(rose,gold,.42+.28*sin(uv.y*6.2+f*2.2+t));float a=(.022+.055*f+.026*g)*halo+.035*ring*(.4+.6*f);gl_FragColor=vec4(col*a,a);}`,program=new Program(gl,{vertex,fragment,transparent:true,uniforms:{uTime:{value:0},uResolution:{value:[1,1]}}}),mesh=new Mesh(gl,{geometry,program});let active=true;const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height));program.uniforms.uResolution.value=[r.width,r.height]};resize();addEventListener('resize',resize,{passive:true});const loop=t=>{if(!active)return;program.uniforms.uTime.value=t*.001;renderer.render({scene:mesh});requestAnimationFrame(loop)};requestAnimationFrame(loop);const obs=new IntersectionObserver(es=>{active=es[0]?.isIntersecting!==false;if(active)requestAnimationFrame(loop)},{threshold:.02});obs.observe(opening);return true}catch(error){console.warn('[D’AUBE V10] OGL fallback',error);return false}}
function initParallax(){if(tier!=='high'||!rose||matchMedia('(prefers-reduced-motion: reduce)').matches)return;rose.addEventListener('pointermove',e=>{const r=rose.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;rose.style.transform=`perspective(1100px) rotateY(${x*5.5}deg) rotateX(${-y*4.5}deg) scale(1.01)`},{passive:true});rose.addEventListener('pointerleave',()=>rose.style.transform='',{passive:true})}
function bindOpenSequence(){document.getElementById('openRose')?.addEventListener('click',()=>{opening.classList.add('is-open');if(motionApi?.animate){motionApi.animate('.reveal-note',{opacity:[0,1],y:[18,0]},{duration:.68,delay:.58,ease:[.2,.8,.2,1]});motionApi.animate('.thorn-frame',{opacity:[.55,.88]},{duration:.9})}},{capture:true})}
await Promise.all([initMotion(),initLenis()]);const ogl=await initOGL();initParallax();bindOpenSequence();console.info('[D’AUBE V10]',{tier,ogl,motion:!!motionApi,lenis:!!lenis});