import V11_STATE from './v11-state.js';
const CDN={three:'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm',theatre:'https://cdn.jsdelivr.net/npm/@theatre/core@0.7.0/+esm',post:'https://cdn.jsdelivr.net/npm/postprocessing@6.39.4/+esm',motion:'https://cdn.jsdelivr.net/npm/motion@13.2.0/+esm',lenis:'https://cdn.jsdelivr.net/npm/lenis@1.3.26/+esm'};
const ROSE_URL='https://cdn.creativeclaw.co/u/218f016f/images/c9eb6d30-ac63-4b3a-a450-7e9a49d1bd59.png';
const DEPTH_URL='https://cdn.creativeclaw.co/u/218f016f/images/7951b930-6e29-46dc-bf20-9228cc63bacd.png';
async function safeImport(url){try{return await import(url)}catch(error){console.warn('[D’AUBE V11] fallback',url,error);return null}}
function canWebGL(){try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}}
function detectTier(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,save=!!navigator.connection?.saveData,mem=Number(navigator.deviceMemory||4),cores=Number(navigator.hardwareConcurrency||4),webgl=canWebGL(),small=innerWidth<720;if(reduced||save||!webgl||mem<=2||cores<=2)return'low';if(mem>=8&&cores>=8&&!small)return'high';return'medium'}
const tier=detectTier();document.body.dataset.vfxTier=tier;document.body.classList.add('vfx-'+tier);
const stage=document.getElementById('roseStage'),opening=document.getElementById('opening'),canvas=document.getElementById('roseCanvas');
let sceneApi=null,motionApi=null,theatreApi=null,lenisInstance=null,timelineValues={cameraZ:5.15,glassY:0,glassOpacity:.93,roseScale:1,distortion:.1,bloom:.14,chromatic:.0008,petalBurst:0,copyReveal:0,lightSweep:.08};
async function initMotion(){if(tier==='low')return;motionApi=await safeImport(CDN.motion);if(!motionApi)return;const{animate,inView,stagger}=motionApi;animate(document.querySelectorAll('.opening-copy>*'),{opacity:[0,1],y:[14,0]},{delay:stagger(.06),duration:.72,ease:[.2,.75,.2,1]});document.querySelectorAll('.vault,.ceremony,.certificate,.faq').forEach(el=>inView(el,()=>animate(el,{opacity:[.45,1],y:[20,0]},{duration:.8,ease:[.2,.78,.2,1]}),{margin:'-8% 0px -8% 0px'}))}
async function initLenis(){if(tier==='low'||matchMedia('(pointer:coarse)').matches||innerWidth<850)return;const mod=await safeImport(CDN.lenis);if(!mod?.default)return;try{lenisInstance=new mod.default({lerp:tier==='high'?.075:.09,smoothWheel:true,wheelMultiplier:.86});const raf=t=>{lenisInstance?.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf)}catch(error){console.warn('[D’AUBE V11] Lenis fallback',error)}}
function makeGradientEnv(THREE){const c=document.createElement('canvas');c.width=512;c.height=256;const g=c.getContext('2d'),grad=g.createLinearGradient(0,0,c.width,0);grad.addColorStop(0,'#ffe5ad');grad.addColorStop(.22,'#8f5631');grad.addColorStop(.55,'#1d1113');grad.addColorStop(.78,'#6c2132');grad.addColorStop(1,'#f1c382');g.fillStyle=grad;g.fillRect(0,0,c.width,c.height);const t=new THREE.CanvasTexture(c);t.mapping=THREE.EquirectangularReflectionMapping;t.colorSpace=THREE.SRGBColorSpace;return t}
async function initThreeScene(){if(tier==='low')return null;const THREE=await safeImport(CDN.three);if(!THREE)return null;const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:tier==='high',powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,tier==='high'?1.65:1.15));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.setClearColor(0x000000,0);
 const scene=new THREE.Scene();scene.environment=makeGradientEnv(THREE);const camera=new THREE.PerspectiveCamera(34,1,.1,30);camera.position.set(0,0,timelineValues.cameraZ);scene.add(new THREE.AmbientLight(0xffe4c7,.62));const key=new THREE.PointLight(0xffd19d,16,18,2);key.position.set(-2.4,2.5,4.2);scene.add(key);const rim=new THREE.PointLight(0xb12b50,10,15,2);rim.position.set(2.4,.8,3.2);scene.add(rim);
 const loader=new THREE.TextureLoader();loader.setCrossOrigin('anonymous');const [roseTex,depthTex]=await Promise.all([loader.loadAsync(ROSE_URL),loader.loadAsync(DEPTH_URL)]);roseTex.colorSpace=THREE.SRGBColorSpace;roseTex.minFilter=THREE.LinearMipmapLinearFilter;roseTex.magFilter=THREE.LinearFilter;depthTex.minFilter=THREE.LinearFilter;depthTex.magFilter=THREE.LinearFilter;
 const planeGeo=new THREE.PlaneGeometry(3.26,4.07,tier==='high'?96:56,tier==='high'?120:72);const relief=new THREE.ShaderMaterial({transparent:true,uniforms:{uMap:{value:roseTex},uDepth:{value:depthTex},uTime:{value:0},uDepthStrength:{value:tier==='high'?.34:.24},uDistortion:{value:timelineValues.distortion},uRoseScale:{value:1},uLightSweep:{value:.08}},vertexShader:`precision highp float;uniform sampler2D uDepth;uniform float uTime;uniform float uDepthStrength;uniform float uDistortion;uniform float uRoseScale;varying vec2 vUv;varying float vDepth;void main(){vUv=uv;float d=texture2D(uDepth,uv).r;vDepth=d;vec3 p=position;p.xy*=uRoseScale;float wave=sin((uv.y*8.0+uTime*.7)+sin(uv.x*6.0))*0.016*uDistortion;p.z+=(d-.34)*uDepthStrength+wave*d;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`,fragmentShader:`precision highp float;uniform sampler2D uMap;uniform float uTime;uniform float uDistortion;uniform float uLightSweep;varying vec2 vUv;varying float vDepth;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec2 uv=vUv;float n=noise(uv*5.0+vec2(uTime*.08,-uTime*.05));vec2 drift=(vec2(n-.5,noise(uv.yx*6.1-uTime*.05)-.5))*0.006*uDistortion*(.35+vDepth);vec4 c=texture2D(uMap,uv+drift);float sweep=smoothstep(.43,.5,1.0-abs((uv.x+uv.y*.12)-fract(uTime*.055)*1.45))*uLightSweep;c.rgb+=vec3(1.0,.72,.4)*sweep*.05*(.25+vDepth);c.rgb*=mix(.94,1.055,vDepth);gl_FragColor=c;}`});const plate=new THREE.Mesh(planeGeo,relief);plate.position.z=0;scene.add(plate);
 // Real refractive dome: MeshPhysicalMaterial uses transmission framebuffer sampling.
 const domeGeo=new THREE.SphereGeometry(1, tier==='high'?64:40, tier==='high'?56:32, 0, Math.PI*2, 0, Math.PI*.73);const domeMat=new THREE.MeshPhysicalMaterial({color:0xfff5e8,transparent:true,opacity:timelineValues.glassOpacity,transmission:.96,thickness:tier==='high'?.48:.28,ior:1.33,roughness:.055,metalness:0,clearcoat:1,clearcoatRoughness:.035,envMapIntensity:1.15,side:THREE.FrontSide,depthWrite:false});const dome=new THREE.Mesh(domeGeo,domeMat);dome.scale.set(.79,1.22,.68);dome.position.set(0,.48,.48);scene.add(dome);
 const baseRing=new THREE.Mesh(new THREE.TorusGeometry(.82,.016,12,72),new THREE.MeshStandardMaterial({color:0xc08a4e,metalness:.75,roughness:.24}));baseRing.rotation.x=Math.PI/2;baseRing.scale.y=.78;baseRing.position.set(0,-.72,.54);scene.add(baseRing);
 const sparkCount=tier==='high'?160:72,sparkGeo=new THREE.BufferGeometry(),sparkPos=new Float32Array(sparkCount*3),sparkSeed=[];for(let i=0;i<sparkCount;i++){const a=Math.random()*Math.PI*2,r=.12+Math.random()*1.2,y=-.55+Math.random()*2.25;sparkPos[i*3]=Math.cos(a)*r*.62;sparkPos[i*3+1]=y;sparkPos[i*3+2]=.45+Math.sin(a)*r*.35;sparkSeed.push(Math.random()*10)}sparkGeo.setAttribute('position',new THREE.BufferAttribute(sparkPos,3));const sparkMat=new THREE.PointsMaterial({color:0xffd8a1,size:tier==='high'?.026:.022,transparent:true,opacity:.7,blending:THREE.AdditiveBlending,depthWrite:false});const sparks=new THREE.Points(sparkGeo,sparkMat);scene.add(sparks);
 const petalGroup=new THREE.Group(),petals=[];const pg=new THREE.PlaneGeometry(.12,.075),pm=new THREE.MeshStandardMaterial({color:0xa7193b,roughness:.58,metalness:.02,side:THREE.DoubleSide});for(let i=0;i<(tier==='high'?22:12);i++){const m=new THREE.Mesh(pg,pm);m.visible=false;petalGroup.add(m);petals.push({m,a:Math.random()*Math.PI*2,r:.28+Math.random()*.7,phase:Math.random(),spin:.5+Math.random()*1.4,side:Math.random()<.5?-1:1})}scene.add(petalGroup);
 let composer=null,bloomEffect=null,chromaticEffect=null;if(tier==='high'){const P=await safeImport(CDN.post);if(P){try{const{EffectComposer,RenderPass,EffectPass,BloomEffect,VignetteEffect,ChromaticAberrationEffect}=P;composer=new EffectComposer(renderer,{frameBufferType:THREE.HalfFloatType});composer.addPass(new RenderPass(scene,camera));bloomEffect=new BloomEffect({intensity:.22,luminanceThreshold:.62,luminanceSmoothing:.45,mipmapBlur:true});chromaticEffect=new ChromaticAberrationEffect({offset:new THREE.Vector2(.0008,.0008)});const vignette=new VignetteEffect({offset:.18,darkness:.33});composer.addPass(new EffectPass(camera,bloomEffect,chromaticEffect,vignette))}catch(error){console.warn('[D’AUBE V11] postprocessing fallback',error);composer=null}}}
 const clock=new THREE.Clock(),pointer={x:0,y:0},target={x:0,y:0};function resize(){const r=stage.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();composer?.setSize(w,h)}resize();addEventListener('resize',resize,{passive:true});if(tier==='high'&&matchMedia('(pointer:fine)').matches)stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect();target.x=((e.clientX-r.left)/r.width-.5)*.22;target.y=((e.clientY-r.top)/r.height-.5)*.13},{passive:true});stage.addEventListener('pointerleave',()=>{target.x=0;target.y=0},{passive:true});
 function applyTimeline(v){timelineValues=v;camera.position.z=v.cameraZ;dome.position.y=.48+v.glassY;domeMat.opacity=v.glassOpacity;relief.uniforms.uDistortion.value=v.distortion;relief.uniforms.uRoseScale.value=v.roseScale;relief.uniforms.uLightSweep.value=v.lightSweep;if(bloomEffect)bloomEffect.intensity=.18+v.bloom*.55;if(chromaticEffect)chromaticEffect.offset.set(v.chromatic,v.chromatic);document.documentElement.style.setProperty('--copy-reveal',String(v.copyReveal));opening.classList.toggle('timeline-copy-visible',v.copyReveal>.45)}
 function render(){const t=clock.getElapsedTime();relief.uniforms.uTime.value=t;pointer.x+=(target.x-pointer.x)*.045;pointer.y+=(target.y-pointer.y)*.045;plate.rotation.y=pointer.x;plate.rotation.x=-pointer.y;dome.rotation.y=pointer.x*.52;dome.rotation.x=-pointer.y*.35;sparks.rotation.y=t*.035;const burst=timelineValues.petalBurst;petals.forEach((p,i)=>{const q=Math.max(0,Math.min(1,(burst-p.phase*.25)*1.22));p.m.visible=q>.03;if(!p.m.visible)return;const ang=p.a+q*p.spin*p.side*2.4,r=p.r*(.4+q*1.1);p.m.position.set(Math.cos(ang)*r, .42+Math.sin(ang)*r*.55-q*q*1.45, .8+Math.sin(ang*.8)*.22);p.m.rotation.set(q*3.2*p.side,ang+q*2.5,q*4.1*p.side);p.m.scale.setScalar(.55+q*.95)});composer?composer.render():renderer.render(scene,camera);requestAnimationFrame(render)}requestAnimationFrame(render);document.body.classList.add('scene-ready');applyTimeline(timelineValues);return{THREE,renderer,scene,camera,applyTimeline,composer,dome,plate}}
async function initTheatre(){if(tier==='low'||!sceneApi)return false;theatreApi=await safeImport(CDN.theatre);if(!theatreApi?.getProject)return false;try{const{getProject,types}=theatreApi,project=getProject('DAUBE First Light V11',{state:V11_STATE}),sheet=project.sheet('Rose Opening'),obj=sheet.object('Rose Scene',{cameraZ:types.number(5.15),glassY:types.number(0),glassOpacity:types.number(.93,{range:[0,1]}),roseScale:types.number(1),distortion:types.number(.1,{range:[0,1]}),bloom:types.number(.14,{range:[0,1]}),chromatic:types.number(.0008),petalBurst:types.number(0,{range:[0,1]}),copyReveal:types.number(0,{range:[0,1]}),lightSweep:types.number(.08,{range:[0,1]})});await project.ready;obj.onValuesChange(values=>sceneApi.applyTimeline(values));window.addEventListener('daube:rose-open',()=>{sheet.sequence.position=0;void sheet.sequence.play({range:[0,6.5],rate:1})});return true}catch(error){console.warn('[D’AUBE V11] Theatre fallback',error);return false}}
function nativeTimelineFallback(){let running=false;window.addEventListener('daube:rose-open',()=>{if(running||!sceneApi)return;running=true;const start=performance.now(),dur=6500,ease=x=>x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2,lerp=(a,b,t)=>a+(b-a)*t;function frame(now){const p=Math.min(1,(now-start)/dur),e=ease(p);const v={cameraZ:lerp(5.15,4.78,e),glassY:lerp(0,.36,Math.max(0,(p-.35)/.4)),glassOpacity:lerp(.93,.26,Math.max(0,(p-.35)/.35)),roseScale:1+Math.sin(Math.min(1,p/.62)*Math.PI)*.07,distortion:.1+Math.sin(Math.min(1,p/.58)*Math.PI)*.5,bloom:.14+Math.sin(Math.min(1,p/.62)*Math.PI)*.48,chromatic:.0008+Math.sin(Math.min(1,p/.58)*Math.PI)*.0034,petalBurst:Math.max(0,Math.min(1,(p-.4)/.22)),copyReveal:Math.max(0,Math.min(1,(p-.56)/.18)),lightSweep:.08+Math.sin(Math.min(1,p/.58)*Math.PI)*.8};sceneApi.applyTimeline(v);if(p<1)requestAnimationFrame(frame);else running=false}requestAnimationFrame(frame)})}
function lowFallback(){document.body.classList.add('scene-fallback');window.addEventListener('daube:rose-open',()=>{document.documentElement.style.setProperty('--copy-reveal','1');opening.classList.add('timeline-copy-visible')})}
await Promise.all([initMotion(),initLenis()]);sceneApi=await initThreeScene();if(sceneApi){const theatreOK=await initTheatre();if(!theatreOK)nativeTimelineFallback()}else lowFallback();
console.info('[D’AUBE V11]',{tier,three:!!sceneApi,theatre:!!theatreApi,motion:!!motionApi,lenis:!!lenisInstance,post:!!sceneApi?.composer});
