(()=>{
const opening=document.getElementById('opening'),sound=document.getElementById('soundToggle'),langBtn=document.getElementById('langToggle'),audio=document.getElementById('classicalScore');
const params=new URLSearchParams(location.search),name=params.get('name')||'Yến Nhi';let lang='en',playing=false,opened=false;
try{lang=localStorage.getItem('daube_lang')||'en'}catch{}
const D={
 en:{open:'A rose, a slow waltz, then the gift.',body:'A classical rose reliquary staged like a miniature salon scene — glass, thorn, gold, paper and first light.',for:'Prepared for',openRose:'Open the reliquary',copy:'Copy personal link',prepared:'The reliquary opens for',enterVault:'Enter the reliquary ↓',vault:'Eight keepsakes, composed as one collection.',congrats:'For',ceremony:'A rose, a slow waltz, and eight keepsakes arranged as a small classical ceremony.',certificateLink:'Keep the certificate →',presented:'Presented to',certBody:'For arriving with first light, entering the rose garden, and becoming part of this little reliquary.',print:'Print certificate',faqTitle:'Only the useful bits.',q1:'What is this page?',a1:'A personalized D’AUBE digital gift experience.',q2:'Can the name change?',a2:'Yes. Add ?name=Your%20Name to the URL.',q3:'Do I need to buy anything?',a3:'No. This is a goodwill digital gift experience.',q4:'What music is playing?',a4:'Claude Debussy’s La plus que lente, performed by La Pianista; attribution and license details are listed above.',sound:'♫ La plus que lente',pause:'❚❚ Pause',copied:'Personal link copied.'},
 vi:{open:'Một đóa hồng, một điệu valse chậm, rồi mới tới món quà.',body:'Một reliquary hoa hồng cổ điển được dàn dựng như một cảnh salon thu nhỏ — kính, gai, vàng cổ, giấy vellum và first light.',for:'Chuẩn bị cho',openRose:'Mở reliquary',copy:'Sao chép link cá nhân',prepared:'Reliquary mở ra cho',enterVault:'Bước vào reliquary ↓',vault:'Tám kỷ vật được phối thành một bộ sưu tập thống nhất.',congrats:'Dành cho',ceremony:'Một đóa hồng, một điệu valse chậm và tám kỷ vật được sắp thành một nghi thức nhỏ.',certificateLink:'Giữ lại chứng nhận →',presented:'Trao tặng cho',certBody:'Vì đã đến cùng first light, bước vào khu vườn hoa hồng và trở thành một phần của reliquary nhỏ này.',print:'In chứng nhận',faqTitle:'Chỉ giữ lại những điều cần biết.',q1:'Trang này là gì?',a1:'Một trải nghiệm quà tặng digital được cá nhân hóa của D’AUBE.',q2:'Có thể đổi tên không?',a2:'Có. Thêm ?name=Ten%20Ban vào URL.',q3:'Có cần mua gì không?',a3:'Không. Đây là trải nghiệm quà tặng thiện chí.',q4:'Nhạc đang phát là gì?',a4:'La plus que lente của Claude Debussy, bản biểu diễn của La Pianista; phần credit và license nằm phía trên.',sound:'♫ La plus que lente',pause:'❚❚ Tạm dừng',copied:'Đã sao chép link cá nhân.'},
 fr:{open:'Une rose, une valse lente, puis le cadeau.',body:'Un reliquaire classique mis en scène comme un petit salon — verre, épines, or ancien, papier et première lumière.',for:'Préparé pour',openRose:'Ouvrir le reliquaire',copy:'Copier le lien personnel',prepared:'Le reliquaire s’ouvre pour',enterVault:'Entrer dans le reliquaire ↓',vault:'Huit souvenirs composés comme une seule collection.',congrats:'Pour',ceremony:'Une rose, une valse lente et huit souvenirs disposés comme une petite cérémonie.',certificateLink:'Garder le certificat →',presented:'Présenté à',certBody:'Pour être arrivé(e) avec la première lumière, être entré(e) dans le jardin de roses et faire partie de ce petit reliquaire.',print:'Imprimer le certificat',faqTitle:'Seulement l’essentiel.',q1:'Qu’est-ce que cette page ?',a1:'Une expérience cadeau numérique personnalisée de D’AUBE.',q2:'Peut-on changer le nom ?',a2:'Oui. Ajoutez ?name=Votre%20Nom à l’URL.',q3:'Faut-il acheter quelque chose ?',a3:'Non. Il s’agit d’un cadeau numérique de gratitude.',q4:'Quelle musique joue ?',a4:'La plus que lente de Claude Debussy, interprétée par La Pianista; les crédits et la licence sont indiqués plus haut.',sound:'♫ La plus que lente',pause:'❚❚ Pause',copied:'Lien personnel copié.'}
};
['recipient','revealName','ceremonyName','certificateName'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=name});
function tr(){const d=D[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-k]').forEach(e=>{const v=d[e.dataset.k];if(v)e.textContent=v});langBtn.textContent=lang.toUpperCase();sound.textContent=playing?d.pause:d.sound;try{localStorage.setItem('daube_lang',lang)}catch{}}
langBtn.addEventListener('click',()=>{lang=lang==='en'?'vi':lang==='vi'?'fr':'en';tr()});
function spawnPetals(){const host=document.querySelector('.petal-field');if(!host||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<16;i++){const p=document.createElement('i'),dx=-90+Math.random()*180,dy=150+Math.random()*220,rot=180+Math.random()*280;p.style.cssText=`position:absolute;left:${22+Math.random()*56}%;top:${17+Math.random()*38}%;width:${8+Math.random()*15}px;height:${6+Math.random()*10}px;border-radius:65% 35% 65% 35%;background:linear-gradient(#d45b76,#72152e);opacity:0;box-shadow:0 8px 16px rgba(91,13,35,.18);animation:daubePetal ${1.6+Math.random()*1.7}s ${Math.random()*.8}s cubic-bezier(.2,.7,.2,1) forwards;--dx:${dx}px;--dy:${dy}px;--rot:${rot}deg`;host.appendChild(p);p.addEventListener('animationend',()=>p.remove())}}
async function playClassical(){if(!audio)return false;try{audio.volume=.22;await audio.play();playing=true;tr();return true}catch(err){document.body.dataset.audioFallback='true';console.warn('[D’AUBE V12] classical recording playback unavailable',err);playing=false;tr();return false}}
function pauseClassical(){audio?.pause();playing=false;tr()}
function openRose(){if(opened)return;opened=true;opening.classList.add('is-open');spawnPetals();void playClassical();window.dispatchEvent(new CustomEvent('daube:rose-open',{detail:{name}}));}
document.getElementById('openRose').addEventListener('click',openRose);
document.getElementById('copyLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);document.getElementById('copyStatus').textContent=D[lang].copied}catch{}});
document.getElementById('printCert').addEventListener('click',()=>print());sound.addEventListener('click',()=>playing?pauseClassical():playClassical());
if(params.get('qa')==='1'&&params.get('autoOpen')==='1')setTimeout(openRose,160);
tr();window.__DAUBE_CORE__={openRose,playClassical,pauseClassical,getName:()=>name};
})();