(()=>{
const q=new URLSearchParams(location.search),name=q.get('name')||'Yến Nhi';
const initials=name.trim().split(/\s+/).map(x=>x[0]||'').slice(-2).join('').toUpperCase()||'YN';
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]));
const palette={ink:'#2b1818',wine:'#6f1831',rose:'#a42749',gold:'#b9894e',paper:'#f6ecdd',cream:'#fffaf1',green:'#354731'};
function vine(x,y,flip=1){return `<g transform="translate(${x} ${y}) scale(${flip} 1)" fill="none" stroke="${palette.green}" stroke-width="2.2" stroke-linecap="round"><path d="M0 170 C24 130 14 82 55 48 C78 30 96 30 112 3"/><path d="M18 132c16-16 28-15 42-10M42 83c16-9 30-8 42 2M69 43c13-10 25-9 35-2"/><path d="M28 110l-12-7m51-40l-12-8m35-31l-10-8"/></g>`}
function seal(cx,cy,r=45){return `<g transform="translate(${cx} ${cy})"><circle r="${r}" fill="${palette.wine}"/><circle r="${r-7}" fill="none" stroke="${palette.gold}" stroke-width="1.3"/><path d="M0-${r-17}V${r-17}M-${r-17} 0H${r-17}" stroke="${palette.gold}" stroke-width="1" opacity=".3"/><text y="10" text-anchor="middle" font-family="Georgia,serif" font-size="${r*.75}" fill="${palette.paper}">☼</text></g>`}
function rose(cx,cy,s=.8){return `<g transform="translate(${cx} ${cy}) scale(${s})"><path d="M0 42C-4 84 1 116-5 153" stroke="${palette.green}" stroke-width="5" fill="none"/><path d="M-4 99c-25-18-43-8-48 12 24 8 40 4 50-6M-3 121c23-16 41-8 47 10-18 9-34 7-46-3" fill="${palette.green}"/><g fill="${palette.rose}" stroke="${palette.wine}" stroke-width="2"><ellipse rx="50" ry="34"/><ellipse rx="37" ry="48" transform="rotate(28)"/><ellipse rx="37" ry="48" transform="rotate(-28)"/><ellipse rx="28" ry="36" fill="#c14562"/><circle r="16" fill="#7f1932"/></g></g>`}
function shell(w,h,body){return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="${palette.paper}"/><rect x="24" y="24" width="${w-48}" height="${h-48}" rx="18" fill="none" stroke="${palette.gold}"/><rect x="35" y="35" width="${w-70}" height="${h-70}" rx="14" fill="none" stroke="${palette.gold}" opacity=".35"/>${vine(42,45)}${vine(w-42,45,-1)}${body}</svg>`}
function download(filename,svg){const b=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
const items=[
 {id:'letter',type:'Letter',title:'Pressed Rose Letter',desc:'A vellum-style thank-you letter marked with your name.',make:()=>shell(1080,1350,`${rose(540,250,1.45)}${seal(540,440,54)}<text x="540" y="565" text-anchor="middle" font-family="Georgia,serif" font-size="66" fill="${palette.ink}">For ${esc(name)}</text><text x="540" y="650" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="34" fill="${palette.wine}">You arrived with first light.</text><text x="540" y="735" text-anchor="middle" font-family="Arial,sans-serif" font-size="25" fill="#6d5547"><tspan x="540" dy="0">May this little rose keep one quiet corner of the day</tspan><tspan x="540" dy="38">for wonder, rest, and the things you still want to make.</tspan></text><text x="540" y="985" text-anchor="middle" font-family="Georgia,serif" font-size="28" fill="${palette.gold}">D’AUBE SONNTAG</text><text x="540" y="1030" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="4" fill="#806d5d">MEANING, MADE VISIBLE.</text>`)},
 {id:'key',type:'Pass',title:'The Thorn Key',desc:'A ceremonial digital pass into the Rose Reliquary.',make:()=>shell(1200,675,`${seal(185,338,72)}<text x="330" y="245" font-family="Arial,sans-serif" font-size="20" letter-spacing="6" fill="${palette.gold}">THE THORN KEY</text><text x="330" y="330" font-family="Georgia,serif" font-size="66" fill="${palette.ink}">${esc(name)}</text><text x="330" y="390" font-family="Georgia,serif" font-style="italic" font-size="30" fill="${palette.wine}">Keeper of First Light</text><text x="330" y="470" font-family="Arial,sans-serif" font-size="19" letter-spacing="3" fill="#776252">RELIQUARY PASS · 2026 · ${esc(initials)}</text>`)},
 {id:'invite',type:'Invitation',title:'Garden Invitation',desc:'A classical salon invitation for the First Light Garden.',make:()=>shell(1080,1350,`${seal(540,270,58)}<text x="540" y="440" text-anchor="middle" font-family="Arial,sans-serif" font-size="20" letter-spacing="6" fill="${palette.gold}">YOU ARE INVITED</text><text x="540" y="560" text-anchor="middle" font-family="Georgia,serif" font-size="76" fill="${palette.ink}">La Rose de l’Aube</text><text x="540" y="635" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="34" fill="${palette.wine}">A private first-light garden for ${esc(name)}</text>${rose(540,860,1.2)}<text x="540" y="1130" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="4" fill="#776252">D’AUBE SONNTAG · RELIQUARY EDITION</text>`)},
 {id:'crest',type:'Monogram',title:'Rose Monogram Crest',desc:'A personal two-letter crest for covers, profiles and keepsakes.',make:()=>shell(1080,1080,`${rose(540,285,1.1)}<circle cx="540" cy="645" r="190" fill="${palette.cream}" stroke="${palette.gold}" stroke-width="3"/><circle cx="540" cy="645" r="168" fill="none" stroke="${palette.wine}" stroke-width="2"/><text x="540" y="715" text-anchor="middle" font-family="Georgia,serif" font-size="190" fill="${palette.wine}">${esc(initials)}</text><text x="540" y="930" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="5" fill="#776252">LA ROSE DE L’AUBE</text>`)},
 {id:'waltz',type:'Music Card',title:'Valse Keepsake Card',desc:'A card dedicated to Debussy’s La plus que lente.',make:()=>shell(1200,675,`${rose(188,310,.85)}<text x="340" y="215" font-family="Arial,sans-serif" font-size="18" letter-spacing="5" fill="${palette.gold}">A SLOW WALTZ FOR THE GARDEN</text><text x="340" y="310" font-family="Georgia,serif" font-style="italic" font-size="58" fill="${palette.ink}">La plus que lente</text><text x="340" y="372" font-family="Georgia,serif" font-size="32" fill="${palette.wine}">Claude Debussy · L. 121 · 1910</text><text x="340" y="450" font-family="Arial,sans-serif" font-size="20" fill="#776252">Prepared with the rose reliquary for ${esc(name)}</text>`)},
 {id:'herbarium',type:'Herbarium',title:'Midnight Herbarium',desc:'A botanical specimen card for the enchanted rose.',make:()=>shell(1080,1350,`${rose(540,520,2.1)}<text x="540" y="890" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="62" fill="${palette.ink}">Rosa prima luce</text><text x="540" y="950" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="4" fill="${palette.gold}">SPECIMEN I · FIRST LIGHT GARDEN</text><text x="540" y="1035" text-anchor="middle" font-family="Georgia,serif" font-size="29" fill="${palette.wine}">Collected for ${esc(name)}</text><text x="540" y="1110" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" fill="#776252">crimson petals · thorned stem · dawn glass</text>`)},
 {id:'wallpaper',type:'Wallpaper',title:'Reliquary Wallpaper',desc:'The cinematic rose hero in its full-resolution original.',url:'https://cdn.creativeclaw.co/u/218f016f/images/c9eb6d30-ac63-4b3a-a450-7e9a49d1bd59.png'},
 {id:'certificate',type:'Certificate',title:'Golden Ceremony Certificate',desc:'A print-ready personalized certificate inside the page.',action:'print'}
];
const grid=document.getElementById('giftGrid');if(!grid)return;
grid.innerHTML=items.map((x,i)=>`<article class="artifact" data-artifact="${x.id}"><div class="artifact-number">0${i+1}</div><div class="artifact-mark">${i%2?'❦':'✦'}</div><div><span>${x.type}</span><h3>${x.title}</h3><p>${x.desc}</p></div><button class="artifact-action" data-id="${x.id}">${x.url?'Open':'Create'} ${x.type.toLowerCase()} ↗</button></article>`).join('');
const byId=Object.fromEntries(items.map(x=>[x.id,x]));grid.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const x=byId[b.dataset.id];if(!x)return;if(x.url){window.open(x.url,'_blank','noopener');return}if(x.action==='print'){document.getElementById('certificate')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>print(),700);return}download(`DAUBE-${x.id}-${initials}.svg`,x.make())});
const cp=document.getElementById('crestPreview');if(cp)cp.querySelector('strong').textContent=initials;
window.__DAUBE_GIFTS__={items:items.map(({make,...x})=>x),initials};
})();