import V12_STATE from './v12-state.js';

const CDN={
  three:'https://cdn.jsdelivr.net/npm/three@0.182.0/+esm',
  theatre:'https://cdn.jsdelivr.net/npm/@theatre/core@0.7.0/+esm',
  post:'https://cdn.jsdelivr.net/npm/postprocessing@6.39.4/+esm',
  quarks:'https://cdn.jsdelivr.net/npm/three.quarks@0.17.1/+esm',
  motion:'https://cdn.jsdelivr.net/npm/motion@13.2.0/+esm',
  lenis:'https://cdn.jsdelivr.net/npm/lenis@1.3.26/+esm'
};
const HERO_URL='https://cdn.creativeclaw.co/u/218f016f/images/3c6689fa-97cc-4e74-9195-e0475a961ede.png';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
async function safeImport(url){try{return await import(url)}catch(error){console.warn('[D’AUBE V14] optional stack fallback',url,error);return null}}
function canWebGL(){try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}}
function detectTier(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,save=!!navigator.connection?.saveData,mem=Number(navigator.deviceMemory||4),cores=Number(navigator.hardwareConcurrency||4),small=innerWidth<720;if(reduced||save||!canWebGL()||mem<=2||cores<=2)return'low';if(mem>=8&&cores>=8&&!small)return'high';return'medium'}
const tier=detectTier();document.body.dataset.vfxTier=tier;document.body.classList.add('vfx-'+tier);
const stage=document.getElementById('roseStage'),opening=document.getElementById('opening'),canvas=document.getElementById('roseCanvas');
let sceneApi=null,theatreApi=null,theatreSheet=null,lenisInstance=null;
let timelineValues={cameraZ:5.36,glassY:0,glassOpacity:.24,roseScale:1,distortion:.05,bloom:.10,chromatic:.00035,petalBurst:0,copyReveal:0,lightSweep:.05};

async function initMotion(){if(tier==='low')return;const M=await safeImport(CDN.motion);if(!M)return;const{animate,inView,stagger}=M;animate(document.querySelectorAll('.opening-copy>*'),{opacity:[0,1],y:[10,0]},{delay:stagger(.045),duration:.62,ease:[.2,.78,.2,1]});document.querySelectorAll('.vault,.collection,.ceremony,.certificate,.credits,.faq').forEach(el=>inView(el,()=>animate(el,{opacity:[.55,1],y:[16,0]},{duration:.72,ease:[.2,.8,.2,1]}),{margin:'-8% 0px -8% 0px'}))}
async function initLenis(){if(tier==='low'||innerWidth<900||matchMedia('(pointer:coarse)').matches)return;const mod=await safeImport(CDN.lenis);if(!mod?.default)return;try{lenisInstance=new mod.default({lerp:.085,smoothWheel:true,wheelMultiplier:.82});const raf=t=>{lenisInstance?.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf)}catch(error){console.warn('[D’AUBE V14] Lenis fallback',error)}}

function makePetalTexture(THREE){const c=document.createElement('canvas');c.width=128;c.height=96;const g=c.getContext('2d');g.clearRect(0,0,128,96);const grad=g.createRadialGradient(48,30,4,62,48,58);grad.addColorStop(0,'#ea7687');grad.addColorStop(.46,'#b42043');grad.addColorStop(1,'#5e0d24');g.fillStyle=grad;g.beginPath();g.moveTo(64,8);g.bezierCurveTo(110,12,126,45,93,76);g.bezierCurveTo(72,94,35,89,15,58);g.bezierCurveTo(3,36,25,13,64,8);g.fill();g.globalAlpha=.32;g.strokeStyle='#ffd0cf';g.lineWidth=2;g.beginPath();g.moveTo(63,13);g.bezierCurveTo(61,36,56,61,46,80);g.stroke();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function makeMoteTexture(THREE){const c=document.createElement('canvas');c.width=c.height=64;const g=c.getContext('2d');const grad=g.createRadialGradient(32,32,0,32,32,30);grad.addColorStop(0,'rgba(255,248,219,1)');grad.addColorStop(.25,'rgba(255,213,142,.8)');grad.addColorStop(1,'rgba(255,184,93,0)');g.fillStyle=grad;g.fillRect(0,0,64,64);return new THREE.CanvasTexture(c)}

function clocheBounds(y){const floor=-1.13,top=1.48,n=clamp((y-floor)/(top-floor));const shoulder=Math.sin(Math.PI*clamp(n*1.08));const rx=.76*(.72+.28*shoulder);const rz=.42*(.72+.28*shoulder);return{rx,rz,floor,top}}

function nativeAt(t){const p=clamp(t/7.2),pulse=Math.sin(Math.PI*clamp((p-.18)/.45));return{
 cameraZ:5.36-.36*clamp(p/.8),glassY:.14*clamp((p-.34)/.42),glassOpacity:.24-.10*clamp((p-.38)/.34),roseScale:1+.025*pulse,
 distortion:.05+.18*pulse,bloom:.10+.30*pulse,chromatic:.00035+.0013*pulse,
 petalBurst:clamp((p-.28)/.42),copyReveal:clamp((p-.55)/.20),lightSweep:.05+.58*pulse
}}

async function initThreeScene(){if(tier==='low'||!stage||!canvas)return null;const THREE=await safeImport(CDN.three);if(!THREE)return null;
 const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:tier==='high',powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,tier==='high'?1.55:1.15));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.98;renderer.setClearColor(0x10090b,1);
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(32,1,.1,30);camera.position.set(0,0,timelineValues.cameraZ);
 const texLoader=new THREE.TextureLoader();texLoader.setCrossOrigin('anonymous');const hero=await texLoader.loadAsync(HERO_URL);hero.colorSpace=THREE.SRGBColorSpace;hero.minFilter=THREE.LinearMipmapLinearFilter;hero.magFilter=THREE.LinearFilter;
 const bgMat=new THREE.MeshBasicMaterial({map:hero,toneMapped:false});const bg=new THREE.Mesh(new THREE.PlaneGeometry(2,2),bgMat);bg.position.z=-1.55;scene.add(bg);
 const ambient=new THREE.AmbientLight(0xffe7cd,.75);scene.add(ambient);const key=new THREE.PointLight(0xffc777,13,20,2);key.position.set(-1.8,2.3,3.8);scene.add(key);const rim=new THREE.PointLight(0x9d2448,7,15,2);rim.position.set(1.9,.9,2.6);scene.add(rim);
 const clocheGroup=new THREE.Group();scene.add(clocheGroup);
 const profile=[[-1.14,.78],[-.86,.79],[-.42,.80],[.05,.79],[.45,.74],[.78,.63],[1.05,.47],[1.30,.29],[1.47,.06]].map(([y,r])=>new THREE.Vector2(r,y));
 const domeGeo=new THREE.LatheGeometry(profile,tier==='high'?88:52);const domeMat=new THREE.MeshPhysicalMaterial({color:0xfff8ee,transparent:true,opacity:timelineValues.glassOpacity,transmission:.94,thickness:tier==='high'?.34:.22,ior:1.33,roughness:.028,clearcoat:1,clearcoatRoughness:.02,envMapIntensity:.9,side:THREE.DoubleSide,depthWrite:false});
 const dome=new THREE.Mesh(domeGeo,domeMat);dome.scale.z=.64;dome.position.z=.46;clocheGroup.add(dome);
 const causticMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uSweep:{value:.05}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`precision highp float;varying vec2 vUv;uniform float uTime;uniform float uSweep;void main(){float line=1.0-smoothstep(.0,.095,abs(vUv.x-fract(uTime*.045+.15)));float vign=smoothstep(.02,.28,vUv.x)*smoothstep(.98,.72,vUv.x)*smoothstep(.02,.28,vUv.y)*smoothstep(.98,.72,vUv.y);gl_FragColor=vec4(1.0,.73,.36,line*vign*uSweep*.16);}`});
 const caustic=new THREE.Mesh(new THREE.PlaneGeometry(1.6,2.65),causticMat);caustic.position.set(0,.14,.82);clocheGroup.add(caustic);
 const petalTex=makePetalTexture(THREE),petalGeo=new THREE.PlaneGeometry(.16,.105);const petalMat=new THREE.MeshStandardMaterial({map:petalTex,transparent:true,alphaTest:.03,roughness:.68,metalness:.02,side:THREE.DoubleSide,depthWrite:true});const petals=[];const seedCount=tier==='high'?34:20;for(let i=0;i<seedCount;i++){const m=new THREE.Mesh(petalGeo,petalMat);clocheGroup.add(m);petals.push({m,phase:(i*0.61803398875)%1,spin:.65+((i*37)%11)/10,drift:.2+((i*19)%7)/12,side:i%2?-1:1,rad:.18+((i*13)%9)/18,tilt:.4+((i*23)%8)/10})}
 const settled=[];for(let i=0;i<(tier==='high'?12:7);i++){const m=new THREE.Mesh(petalGeo,petalMat);m.scale.setScalar(.72+((i*11)%5)/8);m.rotation.set(-1.25,.1*i,.6*i);m.position.set(-.45+i*.075,-1.09,.58+((i%3)-1)*.045);clocheGroup.add(m);settled.push(m)}
 let quarks=null;async function initQuarks(){if(tier!=='high')return;const Q=await safeImport(CDN.quarks);if(!Q)return;try{const{BatchedRenderer,ParticleSystem,ConstantValue,IntervalValue,ConstantColor,PointEmitter,RenderMode}=Q;const batch=new BatchedRenderer();scene.add(batch);const moteTex=makeMoteTexture(THREE);const system=new ParticleSystem({duration:5,looping:true,startLife:new IntervalValue(2.8,5.5),startSpeed:new IntervalValue(.015,.07),startSize:new IntervalValue(.015,.045),startColor:new ConstantColor(new THREE.Vector4(1,.78,.45,.58)),maxParticle:90,emissionOverTime:new ConstantValue(16),shape:new PointEmitter(),material:new THREE.MeshBasicMaterial({map:moteTex,transparent:true,opacity:.55,depthWrite:false,blending:THREE.AdditiveBlending}),renderMode:RenderMode.BillBoard});system.emitter.position.set(-.62,.05,.7);scene.add(system.emitter);batch.addSystem(system);quarks={batch,system}}catch(error){console.warn('[D’AUBE V14] Quarks fallback',error)}}await initQuarks();
 let composer=null,bloomEffect=null,chromaticEffect=null;if(tier==='high'){const P=await safeImport(CDN.post);if(P)try{const{EffectComposer,RenderPass,EffectPass,BloomEffect,VignetteEffect,ChromaticAberrationEffect}=P;composer=new EffectComposer(renderer,{frameBufferType:THREE.HalfFloatType});composer.addPass(new RenderPass(scene,camera));bloomEffect=new BloomEffect({intensity:.16,luminanceThreshold:.72,luminanceSmoothing:.4,mipmapBlur:true});chromaticEffect=new ChromaticAberrationEffect({offset:new THREE.Vector2(.00035,.00035)});composer.addPass(new EffectPass(camera,bloomEffect,chromaticEffect,new VignetteEffect({offset:.12,darkness:.22}))) }catch(error){console.warn('[D’AUBE V14] postprocessing fallback',error)}}
 const clock=new THREE.Clock();let qTime=0,clocheX=-.72;
 function resize(){const r=stage.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();composer?.setSize(w,h);const dist=camera.position.z-bg.position.z,viewH=2*Math.tan(THREE.MathUtils.degToRad(camera.fov*.5))*dist,viewW=viewH*camera.aspect,texAspect=16/9;let bw,bh;if(viewW/viewH>texAspect){bw=viewW;bh=viewW/texAspect}else{bh=viewH;bw=viewH*texAspect}bg.scale.set(bw/2,bh/2,1);clocheX=camera.aspect<.9?-.02:camera.aspect<1.2?-.28:-.78;clocheGroup.position.x=clocheX;clocheGroup.position.y=camera.aspect<.9?.03:.02;clocheGroup.scale.setScalar(camera.aspect<.9?1.05:1)}
 resize();addEventListener('resize',resize,{passive:true});
 function applyTimeline(v){timelineValues={...timelineValues,...v};camera.position.z=timelineValues.cameraZ;dome.position.y=timelineValues.glassY;domeMat.opacity=timelineValues.glassOpacity;causticMat.uniforms.uSweep.value=timelineValues.lightSweep;if(bloomEffect)bloomEffect.intensity=.12+timelineValues.bloom*.52;if(chromaticEffect)chromaticEffect.offset.set(timelineValues.chromatic,timelineValues.chromatic);document.documentElement.style.setProperty('--copy-reveal',String(timelineValues.copyReveal));opening.classList.toggle('timeline-copy-visible',timelineValues.copyReveal>.45);resize()}
 function petalCascade(t){const cascade=timelineValues.petalBurst;petals.forEach((p,i)=>{const speed=.085+.012*(i%5),local=(p.phase+t*speed+cascade*.18)%1,b=clocheBounds(1.45-local*2.5),angle=p.side*(1.2+local*5.4)+p.phase*6.28,r=Math.min(b.rx*.76,p.rad+.24*Math.sin(local*Math.PI));let x=Math.cos(angle)*r+Math.sin(t*.7+i)*.035*p.drift,z=.60+Math.sin(angle*.82)*Math.min(b.rz*.68,.24);x=clamp(x,-b.rx*.88,b.rx*.88);const floorMix=clamp((local-.86)/.14),y=(b.top-local*(b.top-b.floor))*(1-floorMix)+(-1.085+.015*(i%4))*floorMix;p.m.visible=cascade>.02||local>.73;p.m.position.set(x,y,z);p.m.rotation.set(local*4.3*p.side+p.tilt,angle+local*1.7,local*5.1*p.side);p.m.scale.setScalar((.66+.34*Math.sin(Math.PI*local))* (.72+.48*cascade));p.m.material.opacity=.45+.5*Math.min(1,cascade+.25)});settled.forEach((m,i)=>{m.visible=cascade>.55;m.material.opacity=clamp((cascade-.55)*2.4)})}
 function render(){const dt=Math.min(.05,clock.getDelta()),t=clock.elapsedTime;causticMat.uniforms.uTime.value=t;qTime+=dt;quarks?.batch?.update(dt);petalCascade(t);dome.rotation.y=Math.sin(t*.23)*.006;dome.rotation.x=Math.sin(t*.17)*.004;clocheGroup.rotation.y=Math.sin(t*.16)*.003;composer?composer.render():renderer.render(scene,camera);requestAnimationFrame(render)}requestAnimationFrame(render);document.body.classList.add('scene-ready');applyTimeline(timelineValues);return{THREE,renderer,scene,camera,applyTimeline,clocheBounds,petalCascade,dome,composer}}

async function initTheatre(){if(tier==='low'||!sceneApi)return false;theatreApi=await safeImport(CDN.theatre);if(!theatreApi?.getProject)return false;try{const{getProject,types}=theatreApi,project=getProject('DAUBE La Rose de l’Aube V14',{state:V12_STATE}),sheet=project.sheet('Rose Opening'),obj=sheet.object('Rose Scene',{cameraZ:types.number(5.22),glassY:types.number(0),glassOpacity:types.number(.24,{range:[0,1]}),roseScale:types.number(1),distortion:types.number(.05,{range:[0,1]}),bloom:types.number(.10,{range:[0,1]}),chromatic:types.number(.00035),petalBurst:types.number(0,{range:[0,1]}),copyReveal:types.number(0,{range:[0,1]}),lightSweep:types.number(.05,{range:[0,1]})});await project.ready;obj.onValuesChange(values=>sceneApi.applyTimeline({...values,glassOpacity:Math.min(.28,values.glassOpacity*.27)}));theatreSheet=sheet;window.addEventListener('daube:rose-open',()=>{sheet.sequence.position=0;void sheet.sequence.play({range:[0,7.2],rate:1})});return true}catch(error){console.warn('[D’AUBE V14] Theatre fallback',error);return false}}
function nativeTimelineFallback(){let running=false;window.addEventListener('daube:rose-open',()=>{if(running||!sceneApi)return;running=true;const start=performance.now();function frame(now){const sec=Math.min(7.2,(now-start)/1000);sceneApi.applyTimeline(nativeAt(sec));if(sec<7.2)requestAnimationFrame(frame)}requestAnimationFrame(frame)})}
function installQa(){window.__DAUBE_QA__={tier,clocheBounds,seek:async value=>{const sec=value>20?value/1000:value;if(theatreSheet){try{theatreSheet.sequence.position=clamp(sec,0,7.2);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return sec}catch{}}sceneApi?.applyTimeline(nativeAt(sec));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return sec},state:()=>({...timelineValues})};const q=new URLSearchParams(location.search);if(q.get('qa')==='1'&&q.has('frame'))setTimeout(()=>window.__DAUBE_QA__.seek(Number(q.get('frame'))||0),700)}

(async()=>{await Promise.all([initMotion(),initLenis()]);sceneApi=await initThreeScene();if(!sceneApi){document.body.dataset.vfxTier='low';document.body.classList.add('vfx-low');installQa();return}const theatreOk=await initTheatre();if(!theatreOk)nativeTimelineFallback();installQa()})().catch(error=>{console.error('[D’AUBE V14] scene boot fallback',error);document.body.dataset.vfxTier='low';document.body.classList.add('vfx-low');installQa()});
