(()=>{
const params=new URLSearchParams(location.search),name=(params.get('name')||'Yến Nhi').trim()||'Yến Nhi';
const recipient=document.getElementById('recipient'),packName=document.getElementById('packName'),audio=document.getElementById('classicalScore'),sound=document.getElementById('soundToggle'),langBtn=document.getElementById('langToggle'),status=document.getElementById('packStatus');
[recipient,packName].forEach(el=>{if(el)el.textContent=name});
let lang='en',playing=false,opened=false;try{lang=localStorage.getItem('daube_gift_lang')||'en'}catch{}
const T={
 en:{eyebrow:'FIRST LIGHT · PRIVATE GIFT',prepared:'A gift prepared for',heroNote:'A rose, a slow waltz, and nine keepsakes arranged only for you.',openGift:'Open your gift',inside:'INSIDE YOUR RELIQUARY',yourPack:'Your First Light Gift Pack',packBody:'Nine digital keepsakes, one classical rose concept, and one complete pack you can keep.',copyLink:'Copy personal link',thankTitle:'Thank you for arriving with first light.',thankBody:'Keep what speaks to you. Leave the rest here. This little reliquary was made to feel personal, not promotional.'},
 vi:{eyebrow:'FIRST LIGHT · QUÀ RIÊNG DÀNH CHO BẠN',prepared:'Một món quà dành cho',heroNote:'Một đóa hồng, một điệu valse chậm và chín kỷ vật được sắp riêng cho bạn.',openGift:'Mở quà của bạn',inside:'BÊN TRONG RELIQUARY',yourPack:'First Light Gift Pack của bạn',packBody:'Chín món quà digital, một concept hoa hồng cổ điển và một gift pack hoàn chỉnh để bạn giữ lại.',copyLink:'Sao chép link cá nhân',thankTitle:'Cảm ơn vì đã đến cùng first light.',thankBody:'Giữ lại điều chạm tới bạn. Phần còn lại cứ để ở đây. Reliquary nhỏ này được làm để cảm thấy riêng tư, không phải quảng cáo.'},
 fr:{eyebrow:'FIRST LIGHT · CADEAU PRIVÉ',prepared:'Un cadeau préparé pour',heroNote:'Une rose, une valse lente et neuf souvenirs composés rien que pour vous.',openGift:'Ouvrir votre cadeau',inside:'DANS VOTRE RELIQUAIRE',yourPack:'Votre First Light Gift Pack',packBody:'Neuf souvenirs numériques, une rose classique et un coffret complet à conserver.',copyLink:'Copier le lien personnel',thankTitle:'Merci d’être arrivé avec la première lumière.',thankBody:'Gardez ce qui vous parle. Laissez le reste ici. Ce petit reliquaire a été pensé comme quelque chose de personnel, jamais promotionnel.'}
};
function tr(){const d=T[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-k]').forEach(el=>{if(d[el.dataset.k])el.textContent=d[el.dataset.k]});langBtn.textContent=lang.toUpperCase();try{localStorage.setItem('daube_gift_lang',lang)}catch{}}
langBtn?.addEventListener('click',()=>{lang=lang==='en'?'vi':lang==='vi'?'fr':'en';tr()});
function buildPetals(){const host=document.querySelector('.petal-window');if(!host||host.childElementCount)return;for(let i=0;i<28;i++){const p=document.createElement('i');p.style.setProperty('--x',(7+((i*37)%84))+'%');p.style.setProperty('--w',(10+(i%5)*2.5)+'px');p.style.setProperty('--dur',(5.2+(i%7)*.62)+'s');p.style.setProperty('--delay',(-i*.31)+'s');p.style.setProperty('--drift1',((-16+((i*19)%33)))+'px');p.style.setProperty('--drift2',((-24+((i*29)%49)))+'px');p.style.setProperty('--drift3',((-32+((i*41)%65)))+'px');host.appendChild(p)}}buildPetals();
async function playScore(){try{audio.volume=.20;await audio.play();playing=true;sound.textContent='❚❚'}catch{playing=false;sound.textContent='♫'}}
function pauseScore(){audio?.pause();playing=false;sound.textContent='♫'}
sound?.addEventListener('click',()=>playing?pauseScore():playScore());
function openGift({scroll=true}={}){if(opened&&scroll){document.getElementById('giftPack')?.scrollIntoView({behavior:'smooth'});return}opened=true;document.body.classList.add('gift-open');void playScore();window.dispatchEvent(new CustomEvent('daube:rose-open',{detail:{name}}));if(scroll){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;setTimeout(()=>document.getElementById('giftPack')?.scrollIntoView({behavior:reduced?'auto':'smooth'}),reduced?250:3200)}}
document.getElementById('openRose')?.addEventListener('click',()=>openGift());
document.getElementById('copyLink')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);status.textContent=lang==='vi'?'Đã sao chép link.':'Personal link copied.'}catch{status.textContent=lang==='vi'?'Không thể sao chép tự động.':'Copy unavailable.'}});
window.__DAUBE_QA__={seek:async sec=>{const t=Number(sec)||0;document.body.dataset.qa='1';document.documentElement.style.setProperty('--qa-offset',`-${Math.max(0,t)}s`);if(t>.05)openGift({scroll:false});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return t},open:()=>openGift({scroll:false}),name};
if(params.get('qa')==='1'){const sec=(Number(params.get('frame'))||0)/1000;setTimeout(()=>window.__DAUBE_QA__.seek(sec),150)}
tr();
})();