const params=new URLSearchParams(location.search),name=(params.get('name')||'Yến Nhi').trim()||'Yến Nhi';
const initials=name.split(/\s+/).map(x=>x[0]||'').slice(-2).join('').toUpperCase()||'YN';
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]));
const A={hero:'https://cdn.creativeclaw.co/u/218f016f/images/7fb47be0-40d3-4011-9d1a-b20756010815.png',badge:'https://cdn.creativeclaw.co/u/218f016f/images/ffffacda-c8f2-4015-81dd-af7e4cb45e50.png',letter:'https://cdn.creativeclaw.co/u/218f016f/images/699514a7-0fb0-4845-937d-c99e81f17423.png',invitation:'https://cdn.creativeclaw.co/u/218f016f/images/e1033a89-80a6-4274-b8de-b416eb83079d.png',herbarium:'https://cdn.creativeclaw.co/u/218f016f/images/8924aadc-ad98-4838-b814-39c42877798d.png',certificate:'https://cdn.creativeclaw.co/u/218f016f/images/5d526c85-ac0d-4ce0-8e9c-6c241dcf647f.png'};
const C={ink:'#2a1816',wine:'#6f1732',rose:'#9f1d3f',gold:'#c99858',paper:'#f6ead8',cream:'#fff9ef',green:'#37462f'};
const shell=(w,h,body)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="p" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fffaf1"/><stop offset="1" stop-color="#ead8bf"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#p)"/><rect x="26" y="26" width="${w-52}" height="${h-52}" rx="18" fill="none" stroke="${C.gold}" stroke-width="2"/><rect x="39" y="39" width="${w-78}" height="${h-78}" rx="14" fill="none" stroke="${C.wine}" opacity=".22"/>${body}</svg>`;
const roseMark=(cx,cy,s=1)=>`<g transform="translate(${cx} ${cy}) scale(${s})"><circle r="62" fill="${C.wine}"/><circle r="52" fill="none" stroke="${C.gold}" stroke-width="2"/><path d="M0-30c29 0 40 21 31 42-7 19-23 34-31 47-8-13-24-28-31-47-9-21 2-42 31-42Z" fill="#b93252"/><text y="10" text-anchor="middle" font-family="Georgia,serif" font-size="36" fill="#fae7ca">✦</text></g>`;
const makeLetter=()=>shell(1080,1350,`${roseMark(540,210,1)}<text x="540" y="365" text-anchor="middle" font-family="Georgia,serif" font-size="64" fill="${C.wine}">Pressed Rose Letter</text><text x="540" y="440" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="34" fill="${C.ink}">For ${esc(name)}</text><text x="540" y="570" text-anchor="middle" font-family="Georgia,serif" font-size="28" fill="#765e50"><tspan x="540">You arrived with first light.</tspan><tspan x="540" dy="44">May this small reliquary keep one quiet corner</tspan><tspan x="540" dy="44">for wonder, rest, and the things you still want to make.</tspan></text><path d="M330 830H750" stroke="${C.gold}"/><text x="540" y="930" text-anchor="middle" font-family="Georgia,serif" font-size="28" fill="${C.wine}">With care, D’AUBE SONNTAG</text><text x="540" y="1010" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" letter-spacing="5" fill="#8d725e">MEANING, MADE VISIBLE.</text>`);
const makeKey=()=>shell(1200,675,`${roseMark(200,338,1.1)}<text x="350" y="220" font-family="Arial,sans-serif" font-size="18" letter-spacing="7" fill="${C.gold}">THE THORN KEY</text><text x="350" y="320" font-family="Georgia,serif" font-style="italic" font-size="70" fill="${C.wine}">${esc(name)}</text><text x="350" y="385" font-family="Georgia,serif" font-size="30" fill="${C.ink}">Keeper of First Light</text><path d="M350 430H1020" stroke="${C.gold}"/><text x="350" y="485" font-family="Arial,sans-serif" font-size="18" letter-spacing="3" fill="#776252">RELIQUARY PASS · ${esc(initials)} · 2026</text>`);
const makeInvite=()=>shell(1080,1350,`${roseMark(540,220,1)}<text x="540" y="390" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="7" fill="${C.gold}">YOU ARE INVITED</text><text x="540" y="510" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="74" fill="${C.wine}">La Rose de l’Aube</text><text x="540" y="595" text-anchor="middle" font-family="Georgia,serif" font-size="34" fill="${C.ink}">A private First Light Garden for</text><text x="540" y="675" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="54" fill="${C.wine}">${esc(name)}</text><path d="M340 760H740" stroke="${C.gold}"/><text x="540" y="850" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="4" fill="#7d6657">ADMIT ONE · GRAND RELIQUARY</text>`);
const makeCrest=()=>shell(1080,1080,`<circle cx="540" cy="505" r="292" fill="#fff8ec" stroke="${C.gold}" stroke-width="5"/><circle cx="540" cy="505" r="258" fill="none" stroke="${C.wine}" stroke-width="2"/><circle cx="540" cy="505" r="220" fill="${C.wine}"/><text x="540" y="570" text-anchor="middle" font-family="Georgia,serif" font-size="200" fill="#f5dfbd">${esc(initials)}</text><text x="540" y="845" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="46" fill="${C.wine}">La Rose de l’Aube</text><text x="540" y="905" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" letter-spacing="6" fill="#806a58">FIRST LIGHT GARDEN</text>`);
const makeMusic=()=>shell(1200,675,`${roseMark(180,338,.95)}<text x="330" y="210" font-family="Arial,sans-serif" font-size="17" letter-spacing="6" fill="${C.gold}">A SLOW WALTZ FOR THE GARDEN</text><text x="330" y="315" font-family="Georgia,serif" font-style="italic" font-size="68" fill="${C.ink}">La plus que lente</text><text x="330" y="375" font-family="Georgia,serif" font-size="30" fill="${C.wine}">Claude Debussy · L.121 · 1910</text><path d="M330 420H1010" stroke="${C.gold}"/><text x="330" y="475" font-family="Arial,sans-serif" font-size="19" fill="#776252">Prepared with the Rose Reliquary for ${esc(name)}</text>`);
const makeHerbarium=()=>shell(1080,1350,`${roseMark(540,220,1.15)}<text x="540" y="390" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="70" fill="${C.wine}">Rosa prima luce</text><text x="540" y="450" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" letter-spacing="5" fill="${C.gold}">SPECIMEN I · FIRST LIGHT GARDEN</text><path d="M540 560C520 690 548 800 520 930" stroke="${C.green}" stroke-width="8"/><circle cx="540" cy="560" r="95" fill="#a92949" stroke="${C.wine}" stroke-width="8"/><path d="M530 760c-90-45-130 10-126 72 72 14 114-10 132-46M526 830c94-38 132 19 120 75-72 8-112-16-124-48" fill="${C.green}"/><text x="540" y="1050" text-anchor="middle" font-family="Georgia,serif" font-size="34" fill="${C.wine}">Collected for ${esc(name)}</text><text x="540" y="1110" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" letter-spacing="3" fill="#7c6655">CRIMSON PETALS · THORNED STEM · DAWN GLASS</text>`);
const makeCertificate=()=>shell(1080,1350,`${roseMark(540,205,1)}<text x="540" y="365" text-anchor="middle" font-family="Georgia,serif" font-size="68" fill="${C.wine}">Certificate of First Light</text><text x="540" y="450" text-anchor="middle" font-family="Arial,sans-serif" font-size="16" letter-spacing="5" fill="${C.gold}">PRESENTED TO</text><text x="540" y="570" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="76" fill="${C.ink}">${esc(name)}</text><path d="M310 640H770" stroke="${C.gold}"/><text x="540" y="730" text-anchor="middle" font-family="Georgia,serif" font-size="27" fill="#765e50"><tspan x="540">For arriving with first light, entering the rose garden,</tspan><tspan x="540" dy="42">and becoming part of this little reliquary.</tspan></text><text x="540" y="970" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" letter-spacing="4" fill="#806a58">GRAND RELIQUARY · 2026</text>`);
const makeBadge=()=>shell(1080,1080,`<circle cx="540" cy="500" r="320" fill="#170b0f" stroke="${C.gold}" stroke-width="8"/><circle cx="540" cy="500" r="282" fill="none" stroke="#e7c797" stroke-width="2"/><text x="540" y="330" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" letter-spacing="6" fill="#e4c08b">LA ROSE DE L’AUBE</text><text x="540" y="565" text-anchor="middle" font-family="Georgia,serif" font-size="170" fill="#e9c999">✦</text><text x="540" y="690" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="44" fill="#f7e9d4">${esc(initials)}</text><text x="540" y="760" text-anchor="middle" font-family="Arial,sans-serif" font-size="16" letter-spacing="5" fill="#c89a5a">FIRST LIGHT GARDEN</text>`);
const items=[
{id:'letter',type:'LETTER',title:'Pressed Rose Letter',desc:'A private thank-you letter set on vellum.',preview:A.letter,make:makeLetter},
{id:'key',type:'PASS',title:'The Thorn Key',desc:'Your ceremonial pass into the Rose Reliquary.',make:makeKey},
{id:'invite',type:'INVITATION',title:'Garden Invitation',desc:'A salon-style invitation reserved in your name.',preview:A.invitation,make:makeInvite},
{id:'crest',type:'MONOGRAM',title:'Rose Monogram Crest',desc:'A personal two-letter heraldic crest.',make:makeCrest},
{id:'waltz',type:'MUSIC CARD',title:'Valse Keepsake Card',desc:'A keepsake for Debussy’s La plus que lente.',make:makeMusic},
{id:'herbarium',type:'HERBARIUM',title:'Rosa prima luce',desc:'The botanical specimen plate of the First Light rose.',preview:A.herbarium,make:makeHerbarium},
{id:'wallpaper',type:'WALLPAPER',title:'Reliquary Wallpaper',desc:'The full cinematic rose scene, ready to keep.',preview:A.hero,asset:A.hero,ext:'png',featured:true},
{id:'certificate',type:'CERTIFICATE',title:'Certificate of First Light',desc:'Your personalized ceremony certificate.',preview:A.certificate,make:makeCertificate},
{id:'badge',type:'BADGE',title:'Official Rose Reliquary Badge',desc:'The heraldic mark of this Grand Garden edition.',preview:A.badge,make:makeBadge}
];
const grid=document.getElementById('giftGrid');
const blobUrls=[];const previewFor=item=>{if(item.preview)return item.preview;const u=URL.createObjectURL(new Blob([item.make()],{type:'image/svg+xml'}));blobUrls.push(u);return u};
if(grid){grid.innerHTML=items.map((item,i)=>`<article class="gift-card${item.featured?' featured':''}" data-gift="${item.id}"><div class="gift-preview"><img src="${previewFor(item)}" alt="${item.title}"><span class="gift-number">${String(i+1).padStart(2,'0')}</span></div><div class="gift-body"><div><small>${item.type}</small><h3>${item.title}</h3><p>${item.desc}</p></div><button class="keep-btn" data-keep="${item.id}" type="button">Keep this gift ↗</button></div></article>`).join('')}
const saveBlob=(name,blob)=>{const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
async function fetchBytes(url){const r=await fetch(url,{mode:'cors'});if(!r.ok)throw new Error('asset '+r.status);return new Uint8Array(await r.arrayBuffer())}
async function keep(item){if(item.asset){try{const bytes=await fetchBytes(item.asset);saveBlob(`DAUBE-${item.id}-${initials}.${item.ext||'png'}`,new Blob([bytes]));return}catch{window.open(item.asset,'_blank','noopener');return}}saveBlob(`DAUBE-${item.id}-${initials}.svg`,new Blob([item.make()],{type:'image/svg+xml;charset=utf-8'}))}
grid?.addEventListener('click',e=>{const b=e.target.closest('[data-keep]');if(!b)return;const item=items.find(x=>x.id===b.dataset.keep);if(item)void keep(item)});
async function downloadPack(){const btn=document.getElementById('downloadPack'),status=document.getElementById('packStatus');btn.disabled=true;status.textContent='Preparing your reliquary…';try{const {zipSync,strToU8}=await import('https://cdn.jsdelivr.net/npm/fflate@0.8.3/+esm');const files={};files['00-READ-ME.txt']=strToU8(`D’AUBE SONNTAG — FIRST LIGHT GIFT PACK\nPrepared for: ${name}\nEdition: La Rose de l’Aube · 2026\n\nMeaning, made visible.\n\nMusic on the gift page: Claude Debussy — La plus que lente, L.121. Performance credit and license details are linked on the page.`);for(const item of items){if(item.asset){try{files[`${String(items.indexOf(item)+1).padStart(2,'0')}-${item.id}.${item.ext||'png'}`]=await fetchBytes(item.asset)}catch{files[`${String(items.indexOf(item)+1).padStart(2,'0')}-${item.id}-link.txt`]=strToU8(item.asset)}}else files[`${String(items.indexOf(item)+1).padStart(2,'0')}-${item.id}.svg`]=strToU8(item.make())}files['gift-manifest.json']=strToU8(JSON.stringify({recipient:name,initials,edition:'V15 Gift Pack',gifts:items.map(x=>({id:x.id,title:x.title,type:x.type}))},null,2));const zipped=zipSync(files,{level:6});saveBlob(`DAUBE-First-Light-Gift-Pack-${initials}.zip`,new Blob([zipped],{type:'application/zip'}));status.textContent='Gift pack ready.'}catch(error){console.error('[D’AUBE V15] pack fallback',error);status.textContent='Full ZIP could not be built here — individual gifts still work.'}finally{btn.disabled=false}}
document.getElementById('downloadPack')?.addEventListener('click',()=>void downloadPack());
window.__DAUBE_GIFTS__={items:items.map(({make,...x})=>x),downloadPack,name,initials,edition:'V15 Gift Pack',assets:A};
addEventListener('beforeunload',()=>blobUrls.forEach(URL.revokeObjectURL));