import { normalizeNotes, nextPage, previousPage } from './journal-core.mjs';
const STORAGE_KEY='daube-journal-concept-v1'; const PAGE_COUNT=4; const app=document.querySelector('#journal-app'); const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const pageMeta=[{kicker:'Entry I',title:'A quiet beginning',prompt:'Write what you want to remember from today…'},{kicker:'Entry II',title:'Between the pages',prompt:'Leave a thought, a fragment, a small promise…'},{kicker:'Entry III',title:'Pressed petals',prompt:'Capture something ordinary before it disappears…'},{kicker:'Entry IV',title:'Last light',prompt:'Close the day with one sentence worth keeping…'}];
function loadNotes(){try{return normalizeNotes(JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'),PAGE_COUNT)}catch{return normalizeNotes([],PAGE_COUNT)}} let notes=loadNotes(); let pageIndex=0; function saveNotes(){localStorage.setItem(STORAGE_KEY,JSON.stringify(notes))}
function escapeText(value){return String(value).replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function renderTabs(){return pageMeta.map((page,index)=>{const active=pageIndex===index+1?' is-active':'';return `<button class="page-tab${active}" data-page-tab="${index+1}" aria-label="Open ${page.kicker}">${index+1}</button>`}).join('')}
function renderCover(){return `<section class="paper cover" data-paper><div class="cover-ornament" aria-hidden="true">✦</div><p class="eyebrow">A small place for slow thoughts</p><h1>The Sunday Journal</h1><p class="cover-copy">A lightweight interaction study: editable pages, browser-local memory, page turns, petals and stardust.</p><button class="primary-action" data-next>Open the journal</button></section>`}
function renderEntry(){const meta=pageMeta[pageIndex-1];const note=notes[pageIndex-1];const finalAction=pageIndex===PAGE_COUNT?'<button class="text-action" data-cover>Return to cover</button>':'';return `<section class="paper entry" data-paper><header><p class="eyebrow">${meta.kicker}</p><h2>${meta.title}</h2></header><label class="sr-only" for="journal-note">Journal text for ${meta.kicker}</label><textarea id="journal-note" data-note maxlength="1200" placeholder="${meta.prompt}">${escapeText(note)}</textarea><footer><span class="save-hint">Saved in this browser</span>${finalAction}</footer></section>`}
function renderShell(){app.innerHTML=`<div class="demo-shell"><div class="proof-badge">D’AUBE Concept Proof — speculative, not client work</div><div class="journal-stage"><div class="effects" aria-hidden="true"></div>${pageIndex===0?renderCover():renderEntry()}<nav class="page-tabs" aria-label="Journal pages">${renderTabs()}</nav></div><div class="toolbar" aria-label="Journal controls"><button data-prev ${pageIndex===0?'disabled':''}>Previous</button><span class="page-status">${pageIndex===0?'Cover':`Page ${pageIndex} of ${PAGE_COUNT}`}</span><button data-next>${pageIndex===PAGE_COUNT?'Cover':'Next'}</button><span class="toolbar-spacer"></span><button data-export>Export notes</button><button class="danger-quiet" data-reset>Reset demo</button></div><p class="prototype-note">Concept scope only. Full promo capture and final asset polish remain reserved for an awarded project.</p></div>`;bindEvents()}
function animateTurn(direction=1){if(reducedMotion.matches)return;const paper=app.querySelector('[data-paper]');if(!paper)return;paper.classList.remove('flip-forward','flip-back');void paper.offsetWidth;paper.classList.add(direction>=0?'flip-forward':'flip-back');burstEffects()}
function burstEffects(){const layer=app.querySelector('.effects');if(!layer||reducedMotion.matches)return;layer.replaceChildren();const count=pageIndex===PAGE_COUNT?18:11;for(let i=0;i<count;i+=1){const spark=document.createElement('i');spark.className=i%3===0?'petal':'stardust';spark.style.setProperty('--x',`${8+Math.random()*84}%`);spark.style.setProperty('--drift',`${-55+Math.random()*110}px`);spark.style.setProperty('--delay',`${Math.random()*.22}s`);spark.style.setProperty('--duration',`${.8+Math.random()*.8}s`);layer.append(spark)}window.setTimeout(()=>layer.replaceChildren(),1900)}
function goTo(next,direction=1){pageIndex=Math.max(0,Math.min(PAGE_COUNT,next));renderShell();animateTurn(direction)}
function exportNotes(){const payload=JSON.stringify({kind:'daube-speculative-journal',notes},null,2);const blob=new Blob([payload],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=Object.assign(document.createElement('a'),{href:url,download:'sunday-journal-notes.json'});anchor.click();URL.revokeObjectURL(url)}
function bindEvents(){app.querySelectorAll('[data-page-tab]').forEach((button)=>button.addEventListener('click',()=>goTo(Number(button.dataset.pageTab),Number(button.dataset.pageTab)>=pageIndex?1:-1)));app.querySelectorAll('[data-next]').forEach((button)=>button.addEventListener('click',()=>goTo(nextPage(pageIndex,PAGE_COUNT),1)));app.querySelector('[data-prev]')?.addEventListener('click',()=>goTo(previousPage(pageIndex,PAGE_COUNT),-1));app.querySelector('[data-cover]')?.addEventListener('click',()=>goTo(0,1));app.querySelector('[data-note]')?.addEventListener('input',(event)=>{notes[pageIndex-1]=event.target.value;saveNotes()});app.querySelector('[data-export]')?.addEventListener('click',exportNotes);app.querySelector('[data-reset]')?.addEventListener('click',()=>{if(!window.confirm('Reset all notes saved by this concept demo?'))return;notes=normalizeNotes([],PAGE_COUNT);localStorage.removeItem(STORAGE_KEY);goTo(0,-1)});app.querySelector('[data-paper]')?.addEventListener('click',(event)=>{if(event.target.closest('textarea,button,a,label'))return;goTo(nextPage(pageIndex,PAGE_COUNT),1)})}
renderShell();
